# Generated by Django 4.0.4 on 2022-07-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passq', '0004_delete_store_alter_contact_options_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'default_permissions': ('add',), 'permissions': (('can comment', 'user can comment'), ('can edit', 'usr can edit comment'))},
        ),
    ]
